### ISSUE TITLE
Provide a full symfony installation with everything configured

### ISSUE THREAD

**Issue by tarioch** [tarioch/eveapi-fetcher-bundle#1]
For people not using symfony for their own project, it could be useful to have a complete standalone application that simply updates the database.

**Comment by Bavragor** [comment]
Any plans for that feature ? Would be a pleasure.

**Comment by tarioch** [comment]
Sorry, currently have the whole project a bit on the back burner as it's right now working fine for what I need it for.
If someone else is willing to setup the standalone one, I'm willing to help/answer questions.
I guess also for most standalone users, yapeal might be the more active solution https://github.com/Yapeal/yapeal

**Comment by Bavragor** [comment]
So I just configured your Bundle (Thank you works like charm)
Maybe you could add the following stuff into your README.md so others would have an easier start ? 

Needed stuff in AppKernel:
```php
            new JMS\DiExtraBundle\JMSDiExtraBundle($this),
            new JMS\AopBundle\JMSAopBundle(),
            new Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle(),
            new Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle(),
            new Mmoreram\GearmanBundle\GearmanBundle(),
            new Tarioch\PhealBundle\TariochPhealBundle(),
            new Tarioch\EveapiFetcherBundle\TariochEveapiFetcherBundle(),
```

Needed stuff in config.yml:
```yaml
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [TariochPhealBundle, TariochEveapiFetcherBundle]

doctrine:
    dbal:
        connections:
                eveapi:
                        driver:   "%database_driver%"
                        host:     "%database_host%"
                        port:     "%database_port%"
                        dbname:   "%database_eveapi_name%"
                        user:     "%database_user%"
                        password: "%database_password%"
                        charset:  UTF8
                        mapping_types:
                                enum: string

    orm:
        entity_managers:
                eveapi:
                        connection: eveapi
                        mappings:
                                TariochEveapiFetcherBundle: ~

doctrine_migrations:
    # workaround, see http://stackoverflow.com/questions/17066670/symfony2-change-migration-directory
    dir_name: '%kernel.root_dir%/../vendor/tarioch/eveapi-fetcher-bundle/Tarioch/EveapiFetcherBundle/DoctrineMigrations'

doctrine_cache:
    providers:
        gearman_cache:
            type: file_system
            namespace: doctrine_cache.ns.gearman

gearman:
    bundles:
        TariochEveapiFetcherBundle:
            name: TariochEveapiFetcherBundle
            active: true
            include:
                - Component/Worker
    defaults:
        method: doNormal
        iterations: 50
        callbacks: false
        job_prefix: null
        generate_unique_key: true
        workers_name_prepend_namespace: false

    servers:
        localhost:
            host: 127.0.0.1
            port: 4730

tarioch_pheal:
    user_agent: Eve-Skilltracker
```

This should help anyone to get started and enjoy your software :)
